import LANGUAGES from "./data/languages.js";

/**
 * Normalise a value that may be a comma-separated string or an array.
 */
function toArray(val) {
  if (!val) return [];
  if (Array.isArray(val)) return val.map(String).filter(Boolean);
  return String(val)
    .split(",")
    .map((v) => v.trim())
    .filter(Boolean);
}

/**
 * Build the full Markdown content of a README for the given language and project params.
 *
 * @param {string} langCode   - one of the LANGUAGES keys (e.g. "en", "fr")
 * @param {object} params     - project information
 * @param {string} params.name
 * @param {string} [params.description]
 * @param {string} [params.repoUrl]
 * @param {string[]} [params.features]
 * @param {string[]} [params.techStack]
 * @param {string} [params.installCommand]
 * @param {string} [params.usageExample]
 * @param {string} [params.license]
 * @param {boolean} [params.includeBadges]
 * @param {boolean} [params.includeToc]
 * @returns {{ markdown: string, language: object }}
 */
export function buildReadme(langCode, params) {
  const lang = LANGUAGES[langCode];
  if (!lang) throw new Error(`Unsupported language code: "${langCode}"`);

  const s = lang.strings;
  const name = params.name || "my-project";
  const slug = name.toLowerCase().replace(/\s+/g, "-");
  const repoUrl = params.repoUrl || `https://github.com/your-username/${slug}`;
  const description = params.description || s.defaultDesc;
  const features = toArray(params.features).length
    ? toArray(params.features)
    : s.defaultFeatures;
  const techStack = toArray(params.techStack);
  const installCmd = params.installCommand || `npm install ${slug}`;
  const usageExample =
    params.usageExample ||
    (langCode === "en"
      ? `# Import the module\nimport ${slug.replace(/-/g, "_")} from "${slug}";\n\n# Use it\n${slug.replace(/-/g, "_")}.run();`
      : `import ${slug.replace(/-/g, "_")} from "${slug}";`);
  const license = params.license || "MIT";
  const includeBadges = params.includeBadges !== false;
  const includeToc = params.includeToc !== false;

  const lines = [];

  // ── Title
  lines.push(`# ${name}`);
  lines.push("");

  // ── Badges
  if (includeBadges) {
    const badgeBase = `https://img.shields.io/badge`;
    lines.push(
      `![License](${badgeBase}/License-${encodeURIComponent(license)}-blue.svg) ` +
        `![Version](${badgeBase}/version-1.0.0-green.svg) ` +
        `![PRs Welcome](${badgeBase}/PRs-welcome-brightgreen.svg)`
    );
    lines.push("");
  }

  // ── Description
  lines.push(description);
  lines.push("");

  // ── Table of Contents
  if (includeToc) {
    lines.push(`## Table of Contents`);
    lines.push("");
    lines.push(`- [${s.overview}](#overview)`);
    lines.push(`- [${s.features}](#features)`);
    if (techStack.length) lines.push(`- [${s.techStack}](#tech-stack)`);
    lines.push(`- [${s.installation}](#installation)`);
    lines.push(`- [${s.usage}](#usage)`);
    lines.push(`- [${s.contributing}](#contributing)`);
    lines.push(`- [${s.license}](#license)`);
    lines.push("");
  }

  // ── Overview
  lines.push(`## ${s.overview}`);
  lines.push("");
  lines.push(description);
  lines.push("");

  // ── Features
  lines.push(`## ${s.features}`);
  lines.push("");
  features.forEach((f) => lines.push(`- ${f}`));
  lines.push("");

  // ── Tech Stack
  if (techStack.length) {
    lines.push(`## ${s.techStack}`);
    lines.push("");
    techStack.forEach((t) => lines.push(`- ${t}`));
    lines.push("");
  }

  // ── Installation
  lines.push(`## ${s.installation}`);
  lines.push("");
  lines.push("```bash");
  lines.push(installCmd);
  lines.push("```");
  lines.push("");

  // ── Usage
  lines.push(`## ${s.usage}`);
  lines.push("");
  lines.push("```js");
  lines.push(usageExample);
  lines.push("```");
  lines.push("");

  // ── Contributing
  lines.push(`## ${s.contributing}`);
  lines.push("");
  lines.push(s.contribBody);
  lines.push("");
  lines.push(`1. Fork the repository`);
  lines.push(`2. Create your branch: \`git checkout -b feature/your-feature\``);
  lines.push(`3. Commit your changes: \`git commit -m "feat: add your feature"\``);
  lines.push(`4. Push to the branch: \`git push origin feature/your-feature\``);
  lines.push(`5. Open a Pull Request`);
  lines.push("");

  // ── License
  lines.push(`## ${s.license}`);
  lines.push("");
  lines.push(s.licenseBody(license));
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push(
    `> Generated by [README Generator API](${repoUrl}) — ${new Date().toISOString().split("T")[0]}`
  );
  lines.push("");

  return {
    markdown: lines.join("\n"),
    language: { code: langCode, name: lang.name, direction: lang.direction },
  };
}

/**
 * Return the list of supported languages (without string internals).
 */
export function listLanguages() {
  return Object.entries(LANGUAGES).map(([code, { name, direction }]) => ({
    code,
    name,
    direction,
  }));
}
